repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      # Run linter
      - id: ruff
        args: [--fix]
      # run formatter
      - id: ruff-format
      
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.2
    hooks:
      - id: commitizen
        stages: [commit-msg]