[tools]
pre-commit = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []

[env]
APP_REPO = 'devop-study-app'
GITOPS_REPO = 'devops-study-apps-gitops'

[hooks]
enter = "bash ./scripts/setup_project"
