name: Backend Build

on:
  pull_request:

jobs:
  build-and-scan:
    name: Build and Scan Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/backend
          file: ./src/backend/Dockerfile
          push: false
          load: true
          tags: backend:${{ github.sha }}

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: backend:${{ github.sha }}
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL